---
- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  when: ansible_pkg_mgr == 'apt'
  become: yes
  become_method: sudo
  notify:
    - reboot
    - waiting for server to come back

- name: Remove useless packages from the cache
  apt:
    autoclean: yes
  when: ansible_pkg_mgr == 'apt'
  become: yes
  become_method: sudo
  notify:
    - reboot
    - waiting for server to come back

