---
- name: Install essentials
  apt: name={{ item }} state=latest
  with_items:
   - tmux
   - vim
   - reptyr
  when: ansible_os_family == 'Debian'
  become: true
  become_method: sudo
  notify:
    - reboot
    - waiting for server to come back
  
