---
- name: Upgrade Packages
  apt:
    upgrade: dist 
  when:
    - ansible_pkg_mgr == 'apt'
    - apt_updated.changed
  async: 1800
  poll: 5
  become: yes
  become_method: sudo
  notify:
    - reboot
    - waiting for server to come back

